name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: raskchanky
          template: classic
          config_timezone: America/Los_Angeles
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes

          # base
          base: header, activity, community, repositories, metadata
          base_hireable: no
          repositories_forks: no
          repositories_affiliations: owner, collaborator
          repositories_skipped: raskchanky/raskchanky

          # plugins
          plugin_stars: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
